

      

steps:
 - task: DownloadPipelineArtifact@2
   inputs:
    artifact: ${{parameters.artifact}}
    path: $(build.artifactstagingdirectory)
 - task: AzureWebApp@1
   displayName: 'Azure Web App Deploy: insight-webapp'
   inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    appType: ${{parameters.apptype}}
    appName: ${{parameters.webapp}}
    package: $(build.artifactstagingdirectory)/**/*.zip
